tap_install:
    sensitive_values: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gfm7h3uggk2e49h7daha80gu54sju6zvqkctzsklhrp0ppsu6cxq8pmjdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSXZGYUpvTmdTRjJzaHZL
            bDNnUW1naW1YVVdTdnpSVlJXZEVNY1ZXajI4ClZxalhUWjFZYkZuejBZdVJudjNm
            aXVTNGJCcFgzeC9RdVY0R2s5M1FQaVkKLS0tIFRyVFlPcFR5MFR3VWg0UU1heTN2
            VXNiVURVenJpV0EyUEh3Sk9jUXc5REUKe27HXVbYMUdyYV4h6uAosSRV8U/Wj29x
            Kas4kgVWOwJK9Z9q5Ki+2tnEwnQCWl3ZGDrw4e8OhJije0KDdNORvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-11T19:48:49Z"
    mac: ENC[AES256_GCM,data:uaCb6isc5n0g8Qo/B9zVtukqZUUDjgHvRfNbqXQhFCwZ4icKG6XxkVcQEwoAh6lX6LKQXh/gTdkl2GYhRMETNi4xL69FzJkmkoJCkKxWMLQ28u4efFWIO0Ehkt1aI3eLEPm/j1bUWJ0CwGp9QADwB9IMIvmHI7ZgDeMWThjQIkc=,iv:e4V20RiS2tUwMuxqgrgq11vy7aqQt8iJJuIRwBjdUbo=,tag:BsG7zjUnKq4563MnRilzkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
